### ISSUE TITLE
建议规范一下 commit message

### ISSUE THREAD

**Issue by DiamondYuan** [EhTagTranslation/Database#1]
type<scope>: message

**Comment by OpportunityLiu** [comment]
用API提交的信息是格式化的https://github.com/EhTagTranslation/EhTagConnector 

这些都是手动提交产生的

**Comment by DiamondYuan** [comment]
手动也要注意规范 QAQ

**Comment by OpportunityLiu** [comment]
还是因为懒。。。
这项目之前还是在wiki编辑的，commit message里全是GitHub的默认消息

**Comment by DiamondYuan** [comment]
强烈建议每一个字段都增加一个 id 。防止 tag 以后变化。

**Comment by OpportunityLiu** [comment]
不是很懂你在说什么

**Comment by DiamondYuan** [comment]
> 不是很懂你在说什么

就是给每一个 tag 都分配一个唯一的ID，数据使用放储存的就是 ID。

**Comment by OpportunityLiu** [comment]
没什么好处啊

**Comment by DiamondYuan** [comment]
> 没什么好处啊

假设需要储存的是储存的是英文字符串，那么英文字符串修改后，原来的数据就都没用了。
而且角色名称可能会重复，加上ID就不会重复了。

**Comment by OpportunityLiu** [comment]
怎么就原来数据没用了？
检索也是从英文检索，即使有了id不重复又能怎么样？id又不能当做检索条件
