### ISSUE TITLE
数据库使用 - [ExHentai 中文标签助手]

### ISSUE THREAD

**Issue by SunBrook** [EhTagTranslation/Database#114]
+ 项目名称：ExHentai 中文标签助手
+ 项目主页：https://sleazyfork.org/zh-CN/scripts/441232-exhentai-%E4%B8%AD%E6%96%87%E6%A0%87%E7%AD%BE%E5%8A%A9%E6%89%8B

项目目前赶工完成了基础功能，等全部梳理之后上github，目前使用的翻译数据来自 EHWiKi，奈何数量远远不够，我想申请使用 EhTagslation 的数据库。

**Comment by OpportunityLiu** [comment]
直接用就好了

**Comment by OpportunityLiu** [comment]
最近看了下，挺好的，如果你愿意的话，可以提 PR 把链接加到本项目首页
