### ISSUE TITLE
更改标签 - female:orc

### ISSUE THREAD

**Issue by oliver-zhq** [EhTagTranslation/Database#115]
# [orc] 
+ 名称：半兽人
+ 描述：半兽人（英语：Orc、Ork），音译为奥克、欧克，是奇幻文学作品当中的虚构生物或种族。
+ 外部链接：[Orc](https://en.wikipedia.org/wiki/Orc)

## 备注：

orc的一般印象大概是《魔戒》或者魔兽里那种张的很丑，有獠牙，比较残暴的[形象](https://static.wikia.nocookie.net/eladriells-dd/images/d/d8/Orc.jpg/)。这个形象是不是翻译成半兽人更合适。而且[兽人](https://zh.wikipedia.org/wiki/%E7%8D%B8%E4%BA%BA)是另一个独立的词。

**Comment by oliver-zhq** [comment]
我还是想把这个翻译提出来讨论，大家什么意见？

**Comment by OpportunityLiu** [comment]
这个可以考虑，兽人现在确实很多代指furry了
