### ISSUE TITLE
数据库使用 - [JHenTai]

### ISSUE THREAD

**Issue by jiangtian616** [EhTagTranslation/Database#120]
+ 项目名称：JHenTai
+ 项目主页：https://github.com/jiangtian616/JHenTai

An E-Hentai app for mobile.
E-hentai 的一个移动端app。

**Comment by OpportunityLiu** [comment]
需要在这面帮忙宣传的话，随时欢迎提 PR 来改 README

**Comment by jiangtian616** [comment]
感谢，等应用完善一点后就来🙇‍

**Comment by jiangtian616** [comment]
> 需要在这面帮忙宣传的话，随时欢迎提 PR 来改 README

感谢，等应用完善一点后就来🙇‍

**Comment by honjow** [comment]
🤔🤔
