### ISSUE TITLE
关于elf的译名，感觉使用音译比较恰当.......

### ISSUE THREAD

**Issue by ChloeKurumi** [EhTagTranslation/Database#127]
国内普遍把elf翻译成精灵，本来就是官方不懂瞎翻，搞得很高大上，结果随着媒体的传播，造成文化传播的事故，经常出现把elf，精灵，妖精混用。但elf本来就只是个虚构的种族名而已，和精灵和妖精是两回事，没有实际意义。
精灵是灵体生命体，低级精灵类似发光体，高级点的有人形或其他生物形态。
妖精是带透明翅膀的小型人形种族。
每次elf和以上种族同时出现的时候，都被翻成不同的译名或者混用。
在日语里，elf也是直接采用的音译，和精灵还有妖精区分开来的。既然如此，我们翻译的时候也尽量保持一致，避免混乱。
所以我提倡应该将elf音译成埃尔夫之类的..........

**Comment by OpportunityLiu** [comment]
如果没有更多意见就先close了
