### ISSUE TITLE
[添加/更改]标签 - parody:mirai kamiki[标签]

### ISSUE THREAD

**Issue by dodying** [EhTagTranslation/Database#14]
# [标签] 
+ 名称：parody:mirai kamiki
+ 描述：
+ 外部链接：

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/75627924-6d863c00-5c0f-11ea-9100-8719f6f5efbc.png)

建议还是从这里重定向过去编辑，你的那个 ninghai / pinghai 也不对，master tag 是 ping hai / ning hai。

![图片](https://user-images.githubusercontent.com/13471233/75628083-a246c300-5c10-11ea-85dc-d0b7b39313a4.png)
