### ISSUE TITLE
由于最近 SPAM 过多，添加了账户注册时间限制

### ISSUE THREAD

**Issue by OpportunityLiu** [EhTagTranslation/Database#144]
https://github.com/EhTagTranslation/Editor/commit/92bc1b3a6cb53b7bf0a9c9ee59b313ba8e850569

@xioxin @Mapaler

**Comment by Mapaler** [comment]
什么是SPAM？

**Comment by xioxin** [comment]
被提交了什么 广告吗

**Comment by xioxin** [comment]
无法理解他在做什么 
https://github.com/EhTagTranslation/Database/commits?author=5946464

**Comment by OpportunityLiu** [comment]
最近每个周末都有这种，之前还觉得是不是前端工具哪有问题

**Comment by xioxin** [comment]
就很神奇 好多个是吧汉语添加到别的分类了

**Comment by xioxin** [comment]
还有提交一些空白 issue 不理解。是有人在开发什么脚本？

**Comment by xioxin** [comment]
其中一个人还关注了别人创建了空项目，另一个用户收藏了数据库项目。感觉他们是独立的用户。其他的事空白账户。

**Comment by xioxin** [comment]
有什么地方会自动创建 issues 类似 #139

**Comment by OpportunityLiu** [comment]
> 



> 有什么地方会自动创建 issues 类似 #139

https://ehtt.vercel.app/edit/artist/*new?namespace=language&raw=Chinese

![image](https://user-images.githubusercontent.com/13471233/180763004-63be3c34-5200-45e7-a563-34e2a25138a0.png)

你在这里点提交 issue 讨论就跳到创建 issue 的链接了
