### ISSUE TITLE
搜索“凉”这个字时没有结果

### ISSUE THREAD

**Issue by jiut** [EhTagTranslation/Database#155]
在数据库和eh搜索栏都有这个问题

**Comment by OpportunityLiu** [comment]
为啥要搜索 `凉`？搜索 `凉` 不好吗？

**Comment by OpportunityLiu** [comment]
还有，已经搞成中文的翻译就不要改成日文了吧。。。

dcff069

**Comment by jiut** [comment]
> 为啥要搜索 `凉`？搜索 `凉` 不好吗？
> 
> 搜索 CJK 兼容区的字符找不到任何结果不是很正常。

这个能在输入法中辨别出来吗？

**Comment by OpportunityLiu** [comment]
正经的输入法根本打不出前一个字。。。
中文输入法为啥要输入韩文，还是一个根本不用的多音字，我猜韩文输入法都打不出来。。。

**Comment by OpportunityLiu** [comment]
https://www.zhihu.com/question/20697984
