### ISSUE TITLE
tights标签理解有误，建议回滚为之前翻译的版本

### ISSUE THREAD

**Issue by Ice-Plume** [EhTagTranslation/Database#183]
目前male和female下的tights标签均翻译为“厚连裤袜”，但查看官方的tag定义（https://ehwiki.org/wiki/tights）就知道并非如此。之前的翻译是正确的的，建议回滚。

**Comment by o-liverkk** [comment]
之前的翻译是什么啊

**Comment by Ice-Plume** [comment]
之前好像是“紧身服”，描述大概意思是“超级英雄穿的衣服”，并且有配图

**Comment by o-liverkk** [comment]
紧身服是 leotard。从有tights tag的画廊来看，tights指的是类似兔女郎的那种无袖无裤腿的紧身衣。

这个词很难确切的翻译，至少“厚连裤袜”从字面上是准确的。

**Comment by o-liverkk** [comment]
> 紧身服是 leotard。这个词很难确切的翻译，“西方将各种材质的裤袜都称为厚连裤袜，40D 以下的薄裤袜才称为连裤袜。”这一段描述是非常正确的，所以译成“厚连裤袜”至少从字面上是准确的。
> 
> 根据我的理解，tights 是指完全不透的那种长袜（观感上甚至说不上丝袜，更像是没有裆的裤子），比如这个 ![image](https://user-images.githubusercontent.com/65083224/212534595-71549512-8322-4395-bebe-6be336bb3f68.png) 所以翻译成紧身”衣“也不是很贴切。

我建议"厚连裤袜"也行，不用改了，改了还会和 leotard 分不清。

**Comment by Ice-Plume** [comment]
感觉是ehwiki的锅，里面tights和pantyhose对应的日文都是タイツ。但是对应成“厚连裤袜”还是感觉有点问题，在ehwiki的know the difference页面(https://ehwiki.org/wiki/Know_The_Difference) 也可以看到Tights是分在Clothing-Skintight Clothing下面的，并且解释是“Used primarily by superheroes and are very colorful. Usually include a cape”，而pantyhose和stockings则是在Clothing-Legwear下面。

**Comment by o-liverkk** [comment]
对，pantyhose是能日常穿的衣服，tights 是有特殊目的的衣服，比如马猴烧酒变身。

不过老外区分这两个词似乎还是很清晰的，很少见同时出现这两个词的画廊。

**Comment by o-liverkk** [comment]
不过说这么多解决不了怎么翻译的问题啊！！！

**Comment by ForsakenRei** [comment]
> （[https://ehwiki.org/wiki/tights）](https://ehwiki.org/wiki/tights%EF%BC%89%E5%B0%B1%E7%9F%A5%E9%81%93%E5%B9%B6%E9%9D%9E%E5%A6%82%E6%AD%A4%E3%80%82%E4%B9%8B%E5%89%8D%E7%9A%84%E7%BF%BB%E8%AF%91%E6%98%AF%E6%AD%A3%E7%A1%AE%E7%9A%84%E7%9A%84%EF%BC%8C%E5%BB%BA%E8%AE%AE%E5%9B%9E%E6%BB%9A%E3%80%82)

北美的话pantyhose是指女性穿的薄裤袜，透的。tights一般指的是厚裤袜/长袜（男女都有），有裆没裆都有，除了作为服装还有比如运动啊训练之类穿在腿上的那种，不透。日本也是看薄厚分タイツ和ストッキング但欧洲好像就不分这些全都叫tights了233

danbooru那边则是把tights和pantyhose归为一个tag但实际上也写了distinct from tights which are usually made of non-sheer fabric，综合一下的话我投现在的翻译厚连裤袜一票
