### ISSUE TITLE
更改标签 - other:extraneous ads

### ISSUE THREAD

**Issue by Ice-Plume** [EhTagTranslation/Database#185]
### 名称

外部广告

### 描述

未出现在原始作品中的一张或多张第三方广告/横幅。不应与水印(watermark)或扫描水印(scanmark)混淆。与作品的上传/扫描/上色/去码相关的广告（捐赠链接、网站或委托链接）不符合条件。不适用于原始作品中本就包含的广告。

**Comment by o-liverkk** [comment]
一张广告也算，那汉语的所有本子全命中了。

**Comment by Ice-Plume** [comment]
> 一张广告也算，那汉语的所有本子全命中了。

按我的理解，正常汉化组的招新广告属于“与作品上传相关的广告”，应该是不算的。目前来看这个tag主要用于那些塞一大堆牛皮癣广告的作品。

**Comment by o-liverkk** [comment]
> 新加的？上周扫描都没报告这个
> 
> https://github.com/EhTagTranslation/Database/actions/runs/3909297792

https://forums.e-hentai.org/index.php?showtopic=263560 月初加的

原来还能自动检查哪些标签没翻译么，这么方便

**Comment by o-liverkk** [comment]
> > 一张广告也算，那汉语的所有本子全命中了。
> 
> 按我的理解，正常汉化组的招新广告属于“与作品上传相关的广告”，应该是不算的。目前来看这个tag主要用于那些塞一大堆牛皮癣广告的作品。

管理们的意思是只要有一页是广告都可以被tag，但是在原有页上加广告不算。
