### ISSUE TITLE
数据库使用 - [EhDatabase2dictionary]

### ISSUE THREAD

**Issue by HeavySnowJakarta** [EhTagTranslation/Database#203]
### 项目名称

EhDatabase2dictionary

### 项目主页

https://github.com/HeavySnowJakarta/EhDatabase2Dictionary

### 备注

我计划将 E 站翻译成果转换为各种格式的电子词典，方便各位老斯基在各种场合下直接阅读翻译成果。

目前计划的格式如下：

+ MDict/欧陆格式（mdx+mdd）
+ Lingoes 格式（dl2）
+ Babylon 格式（bbl）
+ 星际译王格式（dict+idx 等）
+ ABBYY Lingvo 格式（lud+lsd）
+ Mac 词典格式（dictionary）
+ Kindle 词典格式（mobi）
+ dictd 服务器数据库（dict+index）

**Comment by HeavySnowJakarta** [comment]
以上是我知道的所有词典格式，有我不知道的请尽情提，在这里提或者去那边发issue都可以。

**Comment by OpportunityLiu** [comment]
https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97 有解析好的 JSON 的
