### ISSUE TITLE
添加标签 - female: hypnosis

### ISSUE THREAD

**Issue by theUtopian666** [EhTagTranslation/Database#242]
### 名称

催眠

### 描述

使他人进入容易接受暗示的恍惚状态

### 外部链接

https://zh.moegirl.org.cn/%E5%82%AC%E7%9C%A0%E8%83%BD%E5%8A%9B

**Comment by theUtopian666** [comment]
mind control这个tag的直译是精神控制，然而在eh的中文tag里翻译成了催眠，然而催眠和精神控制是被包括的关系，催眠只是精神控制中的一个小分类，在这里翻译成催眠是不严谨的。

我个人希望能将mind control的翻译调整成精神控制，然后参考pixiv，加上hypnosis这个tag作为催眠的tag。

以及mind break这个tag直译是精神破坏而不是洗脑，洗脑的话应该使用mindwash或者mindwashing，这是专有词汇了，况且洗脑和精神破坏的区别还是挺大的，甚至精神破坏都不一定属于精神控制这个大分类，使用药物等手段也可以使人精神崩溃。

我认为这会导致一些投稿者错误的理解了tag的意思，填写了错误的tag，导致部分观众点进tag却发现作品中并没有自己想要的内容后，在评论区和另一些认为这么打tag没问题的人吵起来的情况。我希望这种情况越少越好。

我希望这个意见能够传达到eh的相关人员那里。

**Comment by OpportunityLiu** [comment]
你来错地方了
https://forums.e-hentai.org/index.php?showforum=89
