### ISSUE TITLE
更改标签 - female:very long hair

### ISSUE THREAD

**Issue by nmlhzby007** [EhTagTranslation/Database#32]
# [标签] 
+ 名称：very long hair / 超长发
+ 描述： A participant with the majority of their hair being long enough to reach below the belly button or thereabouts. Hair that is prevented from reaching that length due to being tied up does not qualify. / 大部分头发长度在肚脐以下或附近。由于被绑起来而无法达到该长度的头发不算。
+ 外部链接：https://ehwiki.org/wiki/very_long_hair

## 备注：

@EhTagTranslation

**Comment by OpportunityLiu** [comment]
已添加

https://github.com/EhTagTranslation/Database/commit/e7daf82b0c414f4ee645874e12335adbcc043ad5
