### ISSUE TITLE
标签图标无法显示

### ISSUE THREAD

**Issue by XESA2333** [EhTagTranslation/Database#34]
**描述问题**
刚更新了一下浏览器版本，重启后发现有的标签图标无法显示
**相关网址**
https://e-hentai.org/mytags  其他显示标签的地方
**截图**
![捕 获](https://user-images.githubusercontent.com/68879118/93305431-16edf180-f831-11ea-9ef9-9c60d685fa43.JPG)

**环境**

-   系统:  Windows 10-1909
-   浏览器 Chrome 85.0.4183.102（64 位）
-   插件版本 2.0.7

**Comment by OpportunityLiu** [comment]
等解决了再close吧

**Comment by Arunmor1510** [comment]
按理说把新浪图床的地址全部换成https就可以了
新浪图床支持https的

**Comment by OpportunityLiu** [comment]
> 
> 
> 按理说把新浪图床的地址全部换成https就可以了
> 新浪图床支持https的

不支持，带着e站的referer直接403

**Comment by Arunmor1510** [comment]
有两种可能的解决方案
第一个用tva1.sinaimg.cn这个域名
第二个在img标签里加个referrerpolicy="no-referrer"属性
两种方法未经过大量测试，并且以后可能还是会被封禁，但是可作为过渡方案

**Comment by OpportunityLiu** [comment]
> 第一个用tva1.sinaimg.cn这个域名

用这个方案暂时修复了，方案二与这个项目无关了，在markdown里搞这些不合适

https://github.com/EhTagTranslation/Database/commit/7e53c5caf1e852366f3ed8ecc7e3e40b2ab90ab6

**Comment by Mapaler** [comment]
要不要我把tag图标全部传到github上？似乎没有其他人画图标了吧
