### ISSUE TITLE
更改标签 - female:ryona

### ISSUE THREAD

**Issue by Gandum2077** [EhTagTranslation/Database#4]
# ryona
+ 名称：凌虐
+ 描述：对角色实施痛击、电击、束缚。通常低于拷打(torture)的程度。不应与摔角(wrestling)混淆。
+ 外部链接：

## 备注：
关于ryona（日语：リョナ）如何翻译，并没有一个准确的答案。
首先原翻译“哀嚎”并不准确，根据维基百科的解释，ryona指“借由观看女性角色被痛击、电击、束缚、受伤挣扎、哀鸣而激起性快感“，显然词义范围远超过”哀嚎“。
目前有三种翻译方案：
第一种是Pixiv和维基百科采用的——不翻译，直接用罗马拼音”Ryona“。
第二种是翻译为“凌虐”。虽然Pixiv没有“リョナ”的翻译，但是却对“男リョナ”和“逆リョナ“进行了翻译，参考此处，可知”リョナ“被翻译为”凌虐“。此种翻译的缺点是缺少了最重要的”激起性快感“，即”用观看虐待女性来自慰“的含义，导致容易和其他词汇混淆。
第三种是翻译为”虐女萌“。这种翻译含义比较完整，但是属于生造词。
个人推荐翻译为”凌虐“。

**Comment by OpportunityLiu** [comment]
我觉得挺好，方便的话发个pr吧
