### ISSUE TITLE
是否要考虑生成繁中版本release？

### ISSUE THREAD

**Issue by Mapaler** [EhTagTranslation/Database#40]
看 #2 提到的，要不要用 https://github.com/BYVoid/OpenCC 自动转换一份？

或者实现一个用时才转换的功能，在 EhSyringe 里添加转换数据库到繁体按钮。

**Comment by avviz** [comment]
用时再转换吧

**Comment by OpportunityLiu** [comment]
EHS和其他下游项目负责吧
