### ISSUE TITLE
艺术家名称为日文汉字的是否应转换为简体汉字？

### ISSUE THREAD

**Issue by avviz** [EhTagTranslation/Database#44]
如：福岡太朗→福冈太朗
@EhTagTranslation

**Comment by OpportunityLiu** [comment]
我个人是推荐转的，但是如果含有假名的话，需要整个翻译成中文名或全部保持原样。
参考： https://zh.wikipedia.org/wiki/Wikipedia:%E6%97%A5%E8%AF%AD%E4%B8%93%E6%9C%89%E5%90%8D%E8%AF%8D%E7%9A%84%E4%B8%AD%E8%AF%91%E5%8E%9F%E5%88%99

**Comment by Mapaler** [comment]
央视报道日本人肯定会全部翻译成简体汉字，不会保留日文字形，没有汉字的也是音译成简体汉字。
西方媒体报道日本人更是连假名都不会留，会全部写作罗马音。
反过来，日本人报道西方人名，也会全部转成假名，比如 *[ドナルド・ジョン・トランプ（英語: Donald John Trump）](https://ja.wikipedia.org/wiki/%E3%83%89%E3%83%8A%E3%83%AB%E3%83%89%E3%83%BB%E3%83%88%E3%83%A9%E3%83%B3%E3%83%97)*。中国人因为他们能看得懂汉字，会优先写作汉字，并用假名注音。韩国人他们都会先写人家的汉字名字，比如 *[金 正恩（キム・ジョンウン、きん しょうおん、朝: 김정은）](https://ja.wikipedia.org/wiki/%E9%87%91%E6%AD%A3%E6%81%A9)*

所以这其实是符合每个语言区域的规范的。

只是由于这种网友自发补充的数据库，很多人都不认识假名，日本人的艺名又奇奇怪怪，才保留了完全使用日文原文的兜底形式。
