### ISSUE TITLE
請教關於資料使用的合法性

### ISSUE THREAD

**Issue by SachiaLanlus** [EhTagTranslation/Database#63]
您好

想請問一下關於資料使用上的問題。
我因為學術研究上的需求，
需要作品名稱的清單，以及該作品的角色清單。
在因緣際會之下找到了這個repo。
想請問如果我使用這個repo的database的資料來完成我的論文，
而這個論文的成果並不會用做商業用途。
那麼我這樣的使用，是否合乎授權規範呢?
感謝您

**Comment by OpportunityLiu** [comment]
应该没啥问题，但是这数据库里没有你说的 “作品名稱的清單，以及該作品的角色清單” 啊

**Comment by OpportunityLiu** [comment]
需要这种数据为啥不去 bgm.tv 和 myanimelist.net

**Comment by SachiaLanlus** [comment]
我原本是打算直接從本子中的tag去根據parody和character的co-occurrence關係來整理。
但是你推薦的這兩個網站好像也很棒呢
這幾天我來研究一下
謝謝你
