### ISSUE TITLE
关于EHViewer无法使用标签翻译的问题

### ISSUE THREAD

**Issue by Reto911** [EhTagTranslation/Database#8]
现在的EHViewer 1.7.3 已经无法使用标签翻译了（勾选标签翻译后无法显示中文标签），而作者曾说过不会再更新EHViewer，不明白是否与这个有关。
此外，应用中“贡献翻译”的链接指向的是旧的翻译项目，因此也不知道是不是翻译项目的迁移导致了无法使用标签翻译的问题。
各位有什么好办法吗？

**Comment by OpportunityLiu** [comment]
ehviewer用的翻译是自己处理过的，在tag-translation分支里

**Comment by OpportunityLiu** [comment]
我觉得除了fork出来自己改以外没啥好办法了

**Comment by OpportunityLiu** [comment]
不会搞安卓编译，最后我反编译的原版APK改的下载字符串。
https://github.com/Mapaler/EhViewer/releases/latest
翻译下载地址是
https://github.com/Mapaler/EhViewer/tree/tag-translations

_Originally posted by @Mapaler in https://github.com/EhTagTranslation/EhSyringe/issues/88#issuecomment-593402628_
