### ISSUE TITLE
markdown渲染图片在一些不严格的markdown渲染引擎下不写图片alt会产生渲染错误

### ISSUE THREAD

**Issue by VoidxHoshi** [EhTagTranslation/Database#84]
插入图片Markdown语法代码：
```
![图片alt](图片链接 "图片title")
```
不写图片alt可能会有这种情况
如code geass。
在一个第三方阅读器上产生的问题。

**Comment by OpportunityLiu** [comment]
啥问题？没看懂你的描述

或许你应该在第三方那边提 issue，因为本项目的md是在common mark基础上有一些扩展的，第三方没有正确处理确实有可能出问题

**Comment by VoidxHoshi** [comment]
> 啥问题？没看懂你的描述
> 
> 或许你应该在第三方那边提 issue，因为本项目的md是在common mark基础上有一些扩展的，第三方没有正确处理确实有可能出问题

OK
那我去第三方提issue
你关了这个issue吧。

**Comment by OpportunityLiu** [comment]
For ref: https://github.com/honjow/FEhViewer/issues/15
