### ISSUE TITLE
请问在ETE中描述标签，需要引入其他标签说明时。如何限定其命名空间。

### ISSUE THREAD

**Issue by ShuraragiYomiko** [EhTagTranslation/Database#85]
举例：比如我现在想给一个描述中加入group标签，表示“乱交”，但我以`group`引用后，显示的是"团队"。
我去看了female.md下的各种3p标签对group的引用，均正常引用到“乱交”，而文件中也没有别的特别的标记。请问是如何做到的。
![图](https://ehgt.org/ab/65/ab65552a05bad0b3a4dad60e1fe20210899a206a-3746-246-143-png_l.jpg)
![图](https://ehgt.org/e8/e0/e8e020e100ada85b21d0810f509ad67d0463ebf8-3570-227-204-png_l.jpg)
还有比如标签toddlercon这样的不同命名空间，会以不同翻译显示的。如何准确地定位到其中一个。ETE中引用后，只能默认显示成“幼儿”

**Comment by OpportunityLiu** [comment]
现在是优先在同命名空间找，找不到再扩大范围

**Comment by ShuraragiYomiko** [comment]
> 现在是优先在同命名空间找，找不到再扩大范围

好吧，我了解了。谢谢

**Comment by OpportunityLiu** [comment]
过段时间我优化下吧，确实是个问题

**Comment by ShuraragiYomiko** [comment]
> 过段时间我优化下吧，确实是个问题

好的，期待更新。

**Comment by OpportunityLiu** [comment]
弄好了

1. 修正了未指定命名空间时标签引用的检索顺序
2. 可以显式指定引用的标签所在的命名空间 如 `f:group` 或 `female:group`

**Comment by ShuraragiYomiko** [comment]
好快，大佬神速！
