### ISSUE TITLE
以下行为是否违反 license

### ISSUE THREAD

**Issue by DiamondYuan** [EhTagTranslation/Database#9]
开发了一个漫画管理软件，其中一个功能是可以为漫画增加 tag。
一下行为是否违反 license
1. 直接在项目中内嵌 Database ，用户直接使用。（标注来源）。

2. 分发是不附带数据库，提供教程让用户手动下载 Database 并且导入。

3. Fork Database，格式进行转换后发布到 release。用户一键导入新的 GitHub 项目。

 4. 衍生一个开源项目(比如 npm 包），然后在项目中使用。

**Comment by DiamondYuan** [comment]
@OpportunityLiu @Mapaler

**Comment by OpportunityLiu** [comment]
只要标明协议和来源，可以看生成数据库json里的copyright字段

**Comment by DiamondYuan** [comment]
> 只要标明协议和来源，可以看生成数据库json里的copyright字段

如果是收费的软件呢 ？也可以吗？

**Comment by OpportunityLiu** [comment]
那就不行了，具体可以看license，有中文文本的

**Comment by DiamondYuan** [comment]
> 那就不行了，具体可以看license，有中文文本的

我分发时不附带数据库，没有数据库时也有全部功能。
然后提供用户手动导入数据库（任意 JSON 均可）的功能。理论上来说应该是不违反license 的吧。

**Comment by OpportunityLiu** [comment]
其实这个数据库协议还是相对宽松的，但是中间用到维基、萌百和ehwiki的内容，尤其ehwiki还用的是FDL，那个就非常麻烦了

**Comment by OpportunityLiu** [comment]
你要是能想办法绕过FDL，剩下都不是事

**Comment by DiamondYuan** [comment]
> 你要是能想办法绕过FDL，剩下都不是事

谢谢解答。
