### ISSUE TITLE
[添加]标签 - [koikatsu]

### ISSUE THREAD

**Issue by Nigel-NI** [EhTagTranslation/Database#94]
# [misc:koikatsu] 
+ 名称：恋爱活动
+ 描述：《恋爱活动》是由ILLUSION制作的3D恋爱模拟类型日本成人游戏，因其独特的人物自定义功能常被用来进行二次创作，因此使用《恋爱活动》制作的二创角色或剧情也常被标上此标签。
+ 外部链接：

## 备注：

该标签在E-H数据库中现可检索到四百余条结果。

**Comment by OpportunityLiu** [comment]
走错了

https://forums.e-hentai.org/index.php?showtopic=246656

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/140000178-506cd29b-d082-40dc-950b-6a7a87171558.png)

misc 不接受未分类标签
