### ISSUE TITLE
官方原“misc”命名空间发生改变

### ISSUE THREAD

**Issue by Nigel-NI** [EhTagTranslation/Database#98]
如下图所示，现已分为“mixed”、“other”、“temp”等多项，“other”项为原空间中的“技术”类以及 在“male”与“female”空间中无对应标签的如`yukkuri（油库里）`等，继承了原“misc”空间的部分标签，翻译基本上正常显示；“mixed”项为原空间中的“身体、下半身、多人活动”类，部分标签不显示翻译，如`ffm threesome`（待补充）；“Temp”为用户临时标记的、未录入数据库的标签
![image](https://user-images.githubusercontent.com/23294384/144255949-1f2b5b3a-afc0-4c58-b402-aaa50bbafe0e.png)

**Comment by OpportunityLiu** [comment]
https://forums.e-hentai.org/index.php?showtopic=253042

**Comment by OpportunityLiu** [comment]
根据之前的经验，先等 E 站那面修一个星期的 BUG 吧。

@xioxin @Mapaler 这种情况数据库版本应该更新下了 https://github.com/EhTagTranslation/Database/blob/master/version 是不是考虑改成 6

**Comment by OpportunityLiu** [comment]
而且还出现了不是一个字母的命名空间简写，太蛋疼了

**Comment by Mapaler** [comment]
看起来似乎是不涉及到我们的结构改动，但是tag变动应该很多，还是升级数据库版本比较好。不过翻译迁移怎么实现呢？

**Comment by xioxin** [comment]
可能有帮助的链接：https://repo.e-hentai.org/tools.php?act=taggroup&show=9

**Comment by OpportunityLiu** [comment]
感觉没啥问题了

**Comment by OpportunityLiu** [comment]
下游相关：
- EhViewer：
  https://github.com/Mapaler/EhViewer/commit/7916a10c7db3923039641dc2ed882bce2104e043
  https://gitlab.com/NekoInverter/EhViewer/-/issues/143
- E-Viewer：
  https://github.com/OpportunityLiu/E-Viewer/issues/146
